version: "3"
services:
  app:
    image: nginx-proxy-manager-dnsmasq
    build: ./docker
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81' 
      - '2222:2222'
      - '5222:5222'
      - '5223:5223'
      - '5671:5671'
      - '15671:15671'
      - '15674:15674'
#    environment:
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      # Make sure this config.json file exists as per instructions above:
      - ./config.json:/app/config/production.json
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./etc/hosts:/etc/hosts
